{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  PGHOST: {{ .Values.auth.psql_host }}
  PGPASSWORD: {{ .Values.auth.psql_pass }}
  PGUSER: {{ .Values.auth.psql_admin_user }}
{{- end }}