apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  namespace: {{ .Values.psql_namespace }}
spec:
  template:
    spec:
      containers:
      - name: db-setup
        image: schulcloud/infra-tools:{{ .Values.psql.imageTag }}
        command: ["/bin/bash", "-c", "/scripts/config-script"]
        resources: {{ toYaml .Values.psql.resources | nindent 12 }}
        volumeMounts:
        - name: config-script-volume
          mountPath: /scripts
        envFrom:
        - secretRef:
            name: psql-config-secret  
        env:
        - name: DB_NAME
          value: {{ .Values.database.name }}  
      volumes:
      - name: config-script-volume
        configMap:
          name: psql-config-script
          defaultMode: 457
      restartPolicy: Never