{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  KAFKAHOST: {{ .Values.auth.kafka_host }}
{{- end }}