name: Update Semver Tags

on:
  push:
    tags:
      - '*.*.*'
      
permissions:
  contents: write

jobs:
  update-semver-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  #v6.0.3
      
      - name: Update Semver
        uses: dbildungsplattform/action-update-semver@a95e4e5fd00d6f0f5e011846285a0a7958010cdd # use lightweight git tag not to break direct nested workflow calls, see https://github.com/orgs/community/discussions/48693#discussioncomment-6132963
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          major_version_tag_only: false