---
name: Convert Branch Name

on:
  workflow_call:
    inputs:
      branch:
        description: "original branch name"
        required: true
        type: string
    outputs:
      namespace_from_branch:
        description: "branch in namespace compatible fashion"
        value: ${{ jobs.convert_branch_name.outputs.namespace_from_branch }}

jobs:
  convert_branch_name:
    runs-on: ubuntu-latest
    outputs:
      namespace_from_branch: ${{ steps.create_branch_identifier.outputs.namespace_from_branch }}
    steps:
      - id: create_branch_identifier
        shell: bash
        run: |
          temp=$(echo ${{ inputs.branch }} | sed 's@.*/@@' | tr [A-Z] [a-z] | tr _ - | tr \. - | sed 's/\([[:alpha:]]*-[[:digit:]]*\).*/\1/' | cut -c1-63)
          echo "before" ${{ inputs.branch }} "after" $temp
          echo "namespace_from_branch=$temp" >> $GITHUB_OUTPUT