name: Delete Namespace and Databases manually

on:
  workflow_dispatch:
     inputs:
      namespace:
        type: string
        description: Kubernetes namespace to delete, has to start with e.g. spsh-1234
        required: true

jobs:
  check_namespace_input:
    runs-on: ubuntu-latest
    steps:
    - name: Check if namespace is allowed, fails if it does not starts with ticketnr, e.g. spsh-1234
      run: |
        regex_long='^([[:alpha:]]+?-[[:digit:]]+-[[:digit:]]+)'
        regex_short='^([[:alpha:]]+?-[[:digit:]]+)'
        if [[ "${{ github.event.inputs.namespace }}" =~ $regex_long ]]; then
          echo "${BASH_REMATCH[1]}"
        elif [[ "${{ github.event.inputs.namespace }}" =~ $regex_short ]]; then
          echo "${BASH_REMATCH[1]}"
        else
          exit 1
        fi

  delete_databases_and_namespace:
    needs: 
      - check_namespace_input
    uses: dBildungsplattform/spsh-app-deploy/.github/workflows/delete-namespace.yml@5
    with:
      namespace: ${{ github.event.inputs.namespace }}
    secrets:
      SPSH_DEV_KUBECONFIG: ${{ secrets.SPSH_DEV_KUBECONFIG }}

  deletion_successful:
    needs:
      - delete_databases_and_namespace
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deletion of namespace" ${{ github.event.inputs.namespace }} "done" 