name: Delete Kubernetes Namespace

on:
  workflow_call:
    inputs:
      namespace:
        required: true
        description: "Namespace has to start with ticketnr, e.g. spsh-1234"
        type: string
    secrets:
      SPSH_DEV_KUBECONFIG:
        required: true
permissions:
  contents: read

    
jobs:
  delete-namespace:
    runs-on: ubuntu-latest
    steps:
    - name: Check if namespace is allowed, fails if it not starts with ticketnr, e.g. spsh-1234
      run: | 
        regex='^([[:alpha:]]+?-[[:digit:]]+)'
        [[ ${{ inputs.namespace }} =~ $regex ]]
        echo "${BASH_REMATCH[1]}"
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.SPSH_DEV_KUBECONFIG }}

    - name: Configure kubeconfig as tmp file
      run: |
        echo "${{ secrets.SPSH_DEV_KUBECONFIG }}" > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    - name: Delete Kubernetes namespace
      run: |
        kubectl delete namespace ${{ inputs.namespace }} --kubeconfig $(pwd)/kubeconfig || true