name: Delete Kubernetes Namespace

on:
  workflow_call:
    inputs:
      namespace:
        required: true
        description: "Namespace has to start with ticketnr, e.g. spsh-1234"
        type: string
    secrets:
      SPSH_DEV_KUBECONFIG:
        required: true
permissions:
  contents: read

    
jobs:
  delete_namespace:
    runs-on: ubuntu-latest
    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Configure kubeconfig as tmp file
      run: |
        echo "${{ secrets.SPSH_DEV_KUBECONFIG }}" > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    - name: Delete Helm-Charts in Namespace to eliminate all database connections
      run: | 
        # D

    - name: Delete Keycloak instance database
      run: | 
        # D

    - name: Delete SPSH instance database
      run: | 
        # D

    - name: Delete Kubernetes namespace
      run: |
        # Check if namespace exists?
        kubectl delete namespace ${{ inputs.namespace }} --kubeconfig $(pwd)/kubeconfig