---
name: Deploy Action

on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
      user_name:
        required: false
        default: spsh-bot
        type: string
      dbildungs_iam_server_branch:
        required: true
        description: "Has to be main or in format <project>-<ticketnumber>, e.g. spsh-130"
        default: main
        type: string
      dbildungs_iam_client_branch:
        required: true
        description: "Has to be main or in format <project>-<ticketnumber>, e.g. spsh-130"
        default: main
        type: string
      dbildungs_iam_keycloak_branch:
        required: true
        description: "Has to be main or in format <project>-<ticketnumber>, e.g. spsh-130"
        default: main
        type: string
    secrets:
      SPSH_DEV_KUBECONFIG:
        required: true
permissions:
  contents: read

jobs:
  find_dbildungs_iam_server_helm_chart_tag:
    uses: dBildungsplattform/spsh-app-deploy/.github/workflows/find-helm-chart-by-ticket-or-main-in-registry.yml@1
    with:
      github_repository: "dBildungsplattform/helm-charts-registry"
      branch: ${{ inputs.dbildungs_iam_server_branch }}
      chart_name: "dbildungs-iam"
      service_name: "dbildungs-iam-server"

  find_dbildungs_iam_client_helm_chart_tag:
    uses: dBildungsplattform/spsh-app-deploy/.github/workflows/find-helm-chart-by-ticket-or-main-in-registry.yml@1
    with:
      github_repository: "dBildungsplattform/helm-charts-registry"
      branch: ${{ inputs.dbildungs_iam_client_branch }}
      chart_name: "spsh-client"
      service_name: "dbildungs-iam-client"

  find_dbildungs_iam_keycloak_helm_chart_tag:
    uses: dBildungsplattform/spsh-app-deploy/.github/workflows/find-helm-chart-by-ticket-or-main-in-registry.yml@1
    with:
      github_repository: "dBildungsplattform/helm-charts-registry"
      branch: ${{ inputs.dbildungs_iam_keycloak_branch }}
      chart_name: "dbildungscloud-iam-keycloak"
      service_name: "dbildungs-iam-keycloak"

  create_ingress_prefix:
    uses: dBildungsplattform/spsh-app-deploy/.github/workflows/get-branch-meta.yml@1

  create_lowercase_ingress_prefix:
    needs:
    - create_ingress_prefix
    uses: dBildungsplattform/spsh-app-deploy/.github/workflows/branch-to-namespace.yml@1
    with:
      branch: ${{ github.ref_name == 'main' && inputs.namespace || needs.create_ingress_prefix.outputs.ticket }}
    
  create_keycloak_db_name:
    runs-on: ubuntu-latest
    outputs:
      keycloak_db_name: ${{ steps.create_keycloak_db_name.outputs.keycloak_db_name }}
    steps:
      - id: create_keycloak_db_name
        shell: bash
        run: |
          # keycloak db name creation at a single point
          # Change every "." and "-" into "_", then remove all characters that are not alphanumeric, digit or an underscore and cut it on max lenght for postgresql db name
          temp=$(echo "spsh_keycloak_${{ inputs.namespace }}" | tr - _ | tr \. _ | sed 's/[^a-zA-Z0-9_]//g' | cut -c1-63)
          echo "before" ${{ inputs.namespace }} "after" $temp
          echo "keycloak_db_name=$temp" >> $GITHUB_OUTPUT

  create_spsh_app_db_name:
    runs-on: ubuntu-latest
    outputs:
      spsh_app_db_name: ${{ steps.create_spsh_app_db_name.outputs.spsh_app_db_name }}
    steps:
      - id: create_spsh_app_db_name
        shell: bash
        run: |
          # spsh-app db name creation at a single point
          # Change every "." and "-" into "_", then remove all characters that are not alphanumeric, digit or an underscore and cut it on max lenght for postgresql db name
          temp=$(echo "spsh_database_${{ inputs.namespace }}" | tr - _ | tr \. _ | sed 's/[^a-zA-Z0-9_]//g' | cut -c1-63)
          echo "before" ${{ inputs.namespace }} "after" $temp
          echo "spsh_app_db_name=$temp" >> $GITHUB_OUTPUT

  deployment:
    needs: 
      - find_dbildungs_iam_server_helm_chart_tag
      - find_dbildungs_iam_client_helm_chart_tag
      - find_dbildungs_iam_keycloak_helm_chart_tag
      - create_lowercase_ingress_prefix
      - create_keycloak_db_name
      - create_spsh_app_db_name
    runs-on: 'ubuntu-latest'
    env:
      GITHUB_TOKEN: ${{ github.token }}
      KUBECONFIG_FILE: '${{ secrets.SPSH_DEV_KUBECONFIG }}'
    steps:
      - name: Check if namespace is allowed, fails if it not starts with ticketnr, e.g. spsh-1234 or is exactly 'main'
        run: | 
            if ${{ inputs.namespace != 'main' }}; then
              regex='^([[:alpha:]]+?-[[:digit:]]+)'
              [[ ${{ inputs.namespace }} =~ $regex ]]
              echo "${BASH_REMATCH[1]}"
            fi
      - name: checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          repository: 'dBildungsplattform/spsh-app-deploy'
          ref: "DBP-641-Change-Secret-name"

      - name: Set up kubectl and Helm
        uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f #v4.0.0

      - name: Configure kubeconfig as tmp file
        run: |
          echo "${{ secrets.SPSH_DEV_KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig

      - name: Create Kubernetes namespace
        run: |
          kubectl create namespace ${{ inputs.namespace }} --kubeconfig $(pwd)/kubeconfig || true

      - name: Download dbildungs_iam_server Helm chart
        run: |
          wget https://github.com/dBildungsplattform/helm-charts-registry/releases/download/${{ needs.find_dbildungs_iam_server_helm_chart_tag.outputs.helm_chart_tagname }}/${{ needs.find_dbildungs_iam_server_helm_chart_tag.outputs.helm_chart_tagname }}.tgz
          tar -zxvf ${{ needs.find_dbildungs_iam_server_helm_chart_tag.outputs.helm_chart_tagname }}.tgz 

      - name: Download dbildungs_iam_client Helm chart
        run: |
          wget https://github.com/dBildungsplattform/helm-charts-registry/releases/download/${{ needs.find_dbildungs_iam_client_helm_chart_tag.outputs.helm_chart_tagname }}/${{ needs.find_dbildungs_iam_client_helm_chart_tag.outputs.helm_chart_tagname }}.tgz
          tar -zxvf ${{ needs.find_dbildungs_iam_client_helm_chart_tag.outputs.helm_chart_tagname }}.tgz 

      - name: Download dbildungs_iam_keycloak Helm chart
        run: |
          wget https://github.com/dBildungsplattform/helm-charts-registry/releases/download/${{ needs.find_dbildungs_iam_keycloak_helm_chart_tag.outputs.helm_chart_tagname }}/${{ needs.find_dbildungs_iam_keycloak_helm_chart_tag.outputs.helm_chart_tagname }}.tgz
          tar -zxvf ${{ needs.find_dbildungs_iam_keycloak_helm_chart_tag.outputs.helm_chart_tagname }}.tgz 

      # On branches the ticket number is used as image tag. To ensure the pods are restarted
      # and pull the the latest image, we uninstall the helm release first. (Otherwise same tag -> no change)
      # We also need to uninstall all pods to savely recreate the database
      - name: Uninstall all Helm-Charts in the namespace
        run: |     
          # Get list of installed Helm-Charts in namespace 
          LIST_OF_HELM_CHARTS_IN_NAMESPACE="$(helm ls \
          --namespace ${{ inputs.namespace }} \
          --kubeconfig $(pwd)/kubeconfig \
          --short)"

          # Check if list of installed Helm-Charts is empty 
          if [ -z "$LIST_OF_HELM_CHARTS_IN_NAMESPACE" ]; then
            echo "No Helm-Charts found in namespace ${{ inputs.namespace }}, skipping uninstall"
          else
            helm uninstall \
              $LIST_OF_HELM_CHARTS_IN_NAMESPACE \
              --namespace ${{ inputs.namespace }} \
              --kubeconfig $(pwd)/kubeconfig
          fi

      - name: Create dbildungs-iam secret
        run: |
          kubectl --namespace=${{ inputs.namespace }} --kubeconfig $(pwd)/kubeconfig apply -f ./dbildungs-iam-secrets-dev.yaml

      - name: Create keycloak secret
        run: |
          kubectl --namespace=${{ inputs.namespace }} --kubeconfig $(pwd)/kubeconfig apply -f ./keycloak-secret-dev.yaml

      - name: Create Database for Keycloak
        run: |
          # Generate timestamp for job name uniqueness
          DATE=$(date +%Y%m%d%H%M%S)

          # Define job name for Keycloak database creation job
          HELM_KEYCLOAK_JOB_NAME="psql-db-${DATE}-keycloak-${{ needs.create_lowercase_ingress_prefix.outputs.namespace_from_branch }}"

          # Deploy Database for Keycloak
          helm upgrade --install \
            $HELM_KEYCLOAK_JOB_NAME \
            ./charts/postgres_config \
            --namespace ${{ inputs.namespace }} \
            --set auth.existingSecret="psql-config-secret" \
            --kubeconfig $(pwd)/kubeconfig \
            --set database.name=${{ needs.create_keycloak_db_name.outputs.keycloak_db_name }}

      - name: Create Database for SPSH-App
        run: |
          # Generate timestamp for job name uniqueness
          DATE=$(date +%Y%m%d%H%M%S)

          # Define job name for SPSH-App database creation job
          HELM_SPSH_JOB_NAME="psql-db-${DATE}-database-${{ needs.create_lowercase_ingress_prefix.outputs.namespace_from_branch }}"

          # Deploy Database for SPSH-App 
          helm upgrade --install \
            $HELM_SPSH_JOB_NAME \
            ./charts/postgres_config \
            --namespace ${{ inputs.namespace }} \
            --set auth.existingSecret="psql-config-secret" \
            --kubeconfig $(pwd)/kubeconfig \
            --set database.name=${{ needs.create_spsh_app_db_name.outputs.spsh_app_db_name }}
      
      # Wait is needed, dbildungs_iam_server expects keycloak to be up!
      - name: Deploy dbildungs_iam_keycloak Helm chart
        run: |
          helm upgrade --install \
            dbildungscloud-iam-keycloak \
            dbildungscloud-iam-keycloak \
            --namespace ${{ inputs.namespace }} \
            --kubeconfig $(pwd)/kubeconfig \
            --set auth.existingSecret="keycloak" \
            --set keycloakHostname=${{ needs.create_lowercase_ingress_prefix.outputs.namespace_from_branch }}-keycloak.dev.spsh.dbildungsplattform.de \
            --set frontendHostname=${{ needs.create_lowercase_ingress_prefix.outputs.namespace_from_branch }}.dev.spsh.dbildungsplattform.de \
            --set database.name=${{ needs.create_keycloak_db_name.outputs.keycloak_db_name }} \
            --set db.name=${{ needs.create_keycloak_db_name.outputs.keycloak_db_name }} \
            --wait

      - name: Deploy dbildungs_iam_client Helm chart
        run: |
          helm upgrade --install \
            spsh-client \
            spsh-client \
            --namespace ${{ inputs.namespace }} \
            --kubeconfig $(pwd)/kubeconfig \
            --set frontendHostname=${{ needs.create_lowercase_ingress_prefix.outputs.namespace_from_branch }}.dev.spsh.dbildungsplattform.de

      - name: Deploy dbildungs_iam_server Helm chart
        run: |
          helm upgrade --install \
            dbildungs-iam \
            dbildungs-iam \
            --namespace ${{ inputs.namespace }} \
            --kubeconfig $(pwd)/kubeconfig \
            --set auth.existingSecret="dbildungs-iam" \
            --set backendHostname=${{ needs.create_lowercase_ingress_prefix.outputs.namespace_from_branch }}.dev.spsh.dbildungsplattform.de \
            --set keycloakHostname=${{ needs.create_lowercase_ingress_prefix.outputs.namespace_from_branch }}-keycloak.dev.spsh.dbildungsplattform.de \
            --set database.name=${{ needs.create_spsh_app_db_name.outputs.spsh_app_db_name }}  \
            --set db.name=${{ needs.create_spsh_app_db_name.outputs.spsh_app_db_name }}

  run_playwright_tests:
    needs:
      - create_lowercase_ingress_prefix
      - deployment
    uses: dBildungsplattform/schulportal-testautomatisierung/.github/workflows/playwright.yml@main
    with:
      frontendHostname: "${{ needs.create_lowercase_ingress_prefix.outputs.namespace_from_branch }}.dev.spsh.dbildungsplattform.de"
