name: Get and set Branch and sha as GITHUB_OUTPUT 
on:
  workflow_call:

jobs:
  branch_meta:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch_meta.outputs.branch }}
      sha: ${{ steps.extract_branch_meta.outputs.sha }}
      ticket: ${{ steps.extract_branch_meta.outputs.ticket }}
    steps:
      - name: Extract branch meta
        shell: bash
        id: extract_branch_meta
        run: |
          if [ "${{ github.event_name }}" == 'pull_request' ]; then
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
            echo "sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
            regex='^([[:alpha:]]+?-[[:digit:]]+)'
            [[ $branch =~ $regex ]]
            echo "ticket=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
            echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
            regex='^([[:alpha:]]+?-[[:digit:]]+)'
            [[ $branch =~ $regex ]]
            echo "ticket=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          fi

# - name: Extract project-ticketnumber from branch
#   run: |
#     regex='^([[:alpha:]]+?-[[:digit:]]+)'
#     [[ $branch =~ $regex ]]
#     echo "ticket=${BASH_REMATCH[1]}" >> $GITHUB_ENV
#     echo $TICKET_NR
    